name: syncus-finance-casal

services:
  db:
    image: postgres:15-alpine
    container_name: db-couple-finance
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-couple
    restart: always
    environment:
      # O pgAdmin precisa desses dois campos específicos:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db


  api:
    build: ./backend
    container_name: api-couple-finance
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Aqui montamos a URL usando as variáveis do banco
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      ENVIRONMENT: ${ENVIRONMENT:-development}
      SECRET_KEY: ${SECRET_KEY}
      CORS_ORIGINS: ${CORS_ORIGINS:-}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - ./backend:/app

  frontend:
    image: nginx:alpine
    container_name: frontend-couple-finance
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  postgres_data:
